export const environment = {
  production: true,
  BASE_URL: '#{BASE_URL}#',
  AUTH_API_URL: '#{AUTH_API_URL}#',
  AUTH_API_LOGIN_URL: '#{AUTH_API_LOGIN_URL}#',
  AUTH_API_LOGOUT_URL: '#{AUTH_API_LOGOUT_URL}#',
  AUTH_API_REFRESH_URL: '#{AUTH_API_REFRESH_URL}#',
  AUTH_API_ME_URL: '#{AUTH_API_ME_URL}#',
  VACANCIES_API_URL: '#{VACANCIES_API_URL}#',
  VACANCIES_APPLICATIONS_API_URL: '#{VACANCIES_APPLICATIONS_API_URL}#',
  VACANCIES_FAVORITES_API_URL: '#{VACANCIES_FAVORITES_API_URL}#',
  VACANCIES_SET_FAVORITE_API_URL: '#{VACANCIES_SET_FAVORITE_API_URL}#',
};
